version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres-miguel
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-miguel-vol:/var/lib/postgresql/data

volumes:
  postgres-miguel-vol: